### ISSUE TITLE
Please make a new release and make it available via pypi

### ISSUE THREAD

**Issue by spaetz** [ccnmtl/fdfgen#10]
Currently the latest release on pypi is from 2013 and there has been support for python3 in the repository in the meanwhile. It would be awsome if https://pypi.python.org/pypi/fdfgen/ could be updated to a later release.
Thanks.

**Comment by thraxil** [comment]
https://pypi.python.org/pypi/fdfgen/0.12.0

**Comment by spaetz** [comment]
Merci :-)
